# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Multi-stage Dockerfile for clipboard-to-supabase-mcp-helper

# Stage 1: Build
FROM node:lts-alpine AS builder
WORKDIR /app

# Install build dependencies
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src
RUN npm install
RUN npm run build

# Stage 2: Production image
FROM node:lts-alpine
WORKDIR /app

# Copy built artifacts and production dependencies
COPY package.json package-lock.json ./
RUN npm install --production
COPY --from=builder /app/dist ./dist

# Environment defaults
ENV NODE_ENV=production

# Default command: start MCP server in stdio mode
CMD ["node", "dist/server.js"]
